services:
- type: pserv
  repo: https://github.com/aartem70/livekit-assistant

  # Change this to the path containing your Dockerfile
  rootDir: .

  name: livekit-agent
  runtime: docker

  # Free plan is not available for private services
  plan: starter

  # Environment variables are stored in a group
  # created in the Render dashboard.
  envVars:
  - fromGroup: livekit-agent-env
  region: virginia

  # 300s is the standard allowed maximum. Talk to render.com support if you need this increased.
  maxShutdownDelaySeconds: 300

  # Sane defaults
  scaling:
    minInstances: 1
    maxInstances: 4
    targetCPUPercent: 60
    targetMemoryPercent: 60
version: "1"